### ISSUE TITLE
Delete this repo?

### ISSUE THREAD

**Issue by al3x** [RocketChat/rocketchat-server-snap#16]
It seems like development on this repo has stalled. Meanwhile, the [.snapcraft](https://github.com/RocketChat/Rocket.Chat/tree/develop/.snapcraft) directory in the main RC repo is  actively being updated. To prevent confusion, perhaps it would be good to delete this repo? Thanks!

**Comment by mnlbox** [comment]
@Sing-Li @rodrigok I agree with @al3x 👍

**Comment by debdutdeb** [comment]
This is now the primary snap development repository.
