### ISSUE TITLE
Depreacted MongoDB version with snap package

### ISSUE THREAD

**Issue by aceArt-GmbH** [RocketChat/rocketchat-server-snap#29]
### Description:

Latest Snap package is using a deprecated MongoDB Version.

### Steps to reproduce:

1. Install via snap `sudo snap install rocketchat-server`
2. or switch branches to "4.x/stable"
3. Get system message: "MongoDB version 3.6.14 is deprecated, please upgrade your installation."

### Expected behavior:

The used MongoDB version from the snap should not be deprecated.

### Actual behavior:

Version 3.6.14 is installed which is deprecated. No way to update manually as the binary is in the read-only filesystem from snap.

Also there is no information in the docu about the MongoDB version with a snap installation

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.5
- Operating System: Ubuntu 18
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

Is there a way to update manually update?

### Relevant logs:
`
I20211111-13:38:51.275(1) +----------------------------------------------------------------------+ I20211111-13:38:51.276(1) |                              DEPRECATION                             | I20211111-13:38:51.276(1) +----------------------------------------------------------------------+ I20211111-13:38:51.276(1) |                                                                      | I20211111-13:38:51.276(1) |  YOUR CURRENT MONGODB VERSION (3.6.14) IS DEPRECATED.                | I20211111-13:38:51.276(1) |  IT WILL NOT BE SUPPORTED ON ROCKET.CHAT VERSION 5.0.0 AND GREATER,  | I20211111-13:38:51.276(1) |  PLEASE UPGRADE MONGODB TO VERSION 4.2 OR GREATER                    | I20211111-13:38:51.276(1) |                                                                      | I20211111-13:38:51.277(1) +----------------------------------------------------------------------+ `

**Comment by kaincenteno** [comment]
> Everyone, there is no need to revert. The mongo update will happen shortly. You can ignore the deprecation message in the meantime.

will the fix also apply to people that upgrade at a later date?

Thank you for your fast response =)

**Comment by debdutdeb** [comment]
> will the fix also apply to people that upgrade at a later date?

Yes.

**Comment by dillfrescott** [comment]
So I don't have to worry about manually upgrading the mongo DB right? It will do it for me as soon as a fix comes out?

**Comment by debdutdeb** [comment]
Yes exactly :)

**Comment by debdutdeb** [comment]
Keeping it open for now :) Will close it when the update is done. Thanks

**Comment by alokraj68** [comment]
is the update yet out? i also did refresh to 4.x and now getting deprecated error.

**Comment by henrikhj** [comment]
@debdutdeb If it’s a major fix, could you please release a hot fix to remove the incorrect deprecation message in the meantime?
It’s getting quite spammy and admins that don’t either know about this bug or don’t have the technical background are assuming that stuff is broken because of this message.

**Comment by mlanner** [comment]
Is there an expected timeline for the fix? Just ran into the same issue.

**Comment by aceArt-GmbH** [comment]
> Is there an expected timeline for the fix? Just ran into the same issue.

"already working on that"/"shortly" aka never 🙄

"Snaps are one of our biggest install base. [...] As a result we like to spend more time testing before releasing. [...] This gives us time to look for issues so you don't have to."

**Comment by CvH** [comment]
is it possible that bugs like https://github.com/RocketChat/Rocket.Chat/issues/14562 are also not solved because the deployment/updating of the mongo db just don't work ?

> "already working on that"/"shortly" aka never 🙄

that is sadly the new normal, unsolved bugs that hit you everyday are increasing and get not solved :(

**Comment by henrikhj** [comment]
@CvH agree.  This will probably be the nail in the coffin for us not renewing our contract come march.

**Comment by kaincenteno** [comment]
@henrikhj  if you have a contract, have you tried talking with your sales//success representative to let them know? Can you roll back to the previous channel?

**Comment by debdutdeb** [comment]
4.x track has been updated with mongodb 4.2.17 :) it'll either auto update or you can manually refresh. The process can take a while, jfyi.

Closing this now, create a new issue please if you face any issues. Thanks.

**Comment by CvH** [comment]
@debdutdeb likely related, mongo fails to update https://github.com/RocketChat/Rocket.Chat/issues/24124 :)

**Comment by Zwiggelino** [comment]
hi, 
I use a raspberry pi 4 with RaspberryOS 64bit (Buster) . 
With the command:  **sudo snap refresh rocketchat-server --channel=4.x/stable**
 I updated yesterday from 3.18.2 to version 4.1.2. But MongoDB is still version 3.6.23. With the refresh command, no newer version than 4.1.2 is displayed to me. I also get the deprecaded message. How can I update the MongoDB version? Will ARM computers get the update later? Many thanks for your help! Please excuse my bad english.

**Comment by lschiesser** [comment]
I have the same question.
I'm also running Rocket 4.1.2 on a Raspberry Pi 4 with Ubuntu and got the same error message. When can we expect an update for arm, since these tend to take longer?

**Comment by nooblag** [comment]
Hi there, I'm also facing this issue on ARM (Raspberry Pi 4) with Ubuntu Snap install. Changed to 4.x/stable channel and still getting MongoDB depreciated messages.
