### ISSUE TITLE
SNAP RC 4.2.2 GREY SCREEEN

### ISSUE THREAD

**Issue by sarz4fun** [RocketChat/rocketchat-server-snap#31]
Hello everyone,
today snap auto refreshed from 4.1.2 to 4.2.2
After this only a grey screen appears.
can't do anithing, no errors, no logs, only a grey page.
i am on RHEL8 4.18.0-348.2.1.el8_5.x86_64 with snapd.
anyone can help me?
thank you.

p.s: i disabled auto refresh.

**Comment by bleschber** [comment]
lrwxrwxrwx 1 root root 4 Dec 15 06:31 /var/snap/rocketchat-server/current -> 1502
[snap.rocketchat-server.rocketchat-mongo.log](https://github.com/RocketChat/rocketchat-server-snap/files/7721170/snap.rocketchat-server.rocketchat-mongo.log)

**Comment by debdutdeb** [comment]
That shouldn't be there

**Comment by debdutdeb** [comment]
`ls /var/snap/rocketchat-server/current/` please

**Comment by bleschber** [comment]
mongod.conf  OVERWRITE_SETTING_Site_Url.env  Rocker.Chat.Extra.env

**Comment by debdutdeb** [comment]
Ok. Could you show me the logs please

`journalctl -u snap.rocketchat-server.rocketchat-mongo -n 200 | curl -F 'f:1=<-' ix.io`

**Comment by bleschber** [comment]
output was only a single line:

http://ix.io/3Ivs

**Comment by debdutdeb** [comment]
Not seeing any errors

**Comment by bleschber** [comment]
System was operational on 4.1.2 last night when I went to bed, this morning it was broken.

**Comment by debdutdeb** [comment]
`journalctl -u snap.rocketchat-server.rocketchat-server -n 200 | curl -F 'f:1=<-' ix.io` please

**Comment by bleschber** [comment]
http://ix.io/3Ivt

**Comment by bleschber** [comment]
"Dec 15 09:32:28 SRV-CHAT-01 mongod.27017[2136]: 2021-12-15T09:32:28.494-0600 W FTDC     [initandlisten] Error getting directory iterator '/sys/block': Permission denied"

Is this permission denied error normal & expected?  Or is that part of the problem?

**Comment by debdutdeb** [comment]
Could you try this please, on the host, where it is deployed, try `curl http://localhost:3000/api/info`

**Comment by bleschber** [comment]
{"version":"4.2","success":true}

**Comment by debdutdeb** [comment]
Yep rocketchat is running. Are you behind some reverse proxy that's serving as https?

**Comment by bleschber** [comment]
I'm not sure as I didn't do the initial install on this system.

**Comment by debdutdeb** [comment]
What url do you use to connect to the system? Try that now, while keeping console log open, what do you see?

**Comment by bleschber** [comment]
https://chat.kbsi.com

It is open to the web if you want to hit it to see what output it is serving up

**Comment by debdutdeb** [comment]
It is running though @bleschber 🤔 I thought it wasn't?

**Comment by debdutdeb** [comment]
@sarz4fun please go through the commands I've written in comments and send the outputs here, @ mention me so that I get the notification. Will try to reply ASAP. Thanks

**Comment by bleschber** [comment]
Per OP, rocketchat is running and serving up an http page, but just presents a background page and never displays the login screen or anything else.  Here's the output of snap.rocketchat-server.rocketchat-server
[snap.rocketchat-server.rocketchat-server.log](https://github.com/RocketChat/rocketchat-server-snap/files/7721298/snap.rocketchat-server.rocketchat-server.log)

**Comment by bleschber** [comment]
In chrome, with F12, the console is throwing "Failed to load resource: net::ERR_CONNECTION_REFUSED"

**Comment by debdutdeb** [comment]
I'm not sure I'm following or having the same experience.

![image](https://user-images.githubusercontent.com/76006232/146230651-16c57525-4371-43d6-afee-a30c97a4f197.png)

**Comment by debdutdeb** [comment]
The logs are also looking fine

**Comment by bleschber** [comment]
interesting...

**Comment by bleschber** [comment]
What browser (and version) are you using?

**Comment by debdutdeb** [comment]
Try from igcognito, clear cache. Let me know what happens.

Also, server looks responsive as well.

```
[debdut@Rocket ~]$ curl https://chat.kbsi.com/api/info
{"version":"4.2","success":true}
```

**Comment by debdutdeb** [comment]
> What browser (and version) are you using?

Chrome 96.0.4664.45

**Comment by bleschber** [comment]
@debdutdeb no luck.  same result.  I've tried multiple systems both inside and outside my organization, and systems a different locations to see if it was an ISP problem.  Any idea why it would work for you but not elsewhere?  Anything specific on your system that would allow it to work?  Do you by chance have a running instance of rocket chat running on that same system that the web code could be hitting that would make it work for you?  Just searching for ideas.

**Comment by bleschber** [comment]
Would you have any idea what would cause this: 
POST http://localhost:3000/__meteor__/dynamic-import/fetch net::ERR_CONNECTION_REFUSED

**Comment by debdutdeb** [comment]
Could you, try this please, `sudo snap set rocketchat-server siteurl=https://chat.kbsi.com && sudo snap restart rocketchat-server`

**Comment by bleschber** [comment]
That fixed it!!!

**Comment by bleschber** [comment]
Hopefully that is the same fix for @sarz4fun

**Comment by debdutdeb** [comment]
This is not good. Just a self note. Anyway thanks for being patient @bleschber

**Comment by sarz4fun** [comment]
> Hopefully that is the same fix for @sarz4fun

Sorry but i downgraded to 4.1.2 and restored last backup as soon as possible.
auto snap refresh makes me a bad surprise, i was in stable channel.
should i wait for next stable?

**Comment by sarz4fun** [comment]
> > Hopefully that is the same fix for @sarz4fun
> 
> Sorry but i downgraded to 4.1.2 and restored last backup as soon as possible. auto snap refresh makes me a bad surprise, i was in stable channel. should i wait for next stable?

Updated to current version and fix worked for me. thank you.

**Comment by debdutdeb** [comment]
Thanks for confirming @sarz4fun :) closing this then.

**Comment by wilkis3** [comment]
I had the same issue with a standalone installation of Rocket.Chat 4.2.2 from stable channel. @debdutdeb is your command, to solve this issue, documented at another place?
