### ISSUE TITLE
MongoDB shell access broken after 4.2.2 snap upgrade

### ISSUE THREAD

**Issue by bleschber** [RocketChat/rocketchat-server-snap#32]
**Technique:**
https://docs.rocket.chat/quick-start/installing-and-updating/snaps#how-do-i-access-the-mongodb-shell

**Symptom:**
root@SRV-CHAT-01:~# sudo rocketchat-server.mongo                                    
MongoDB shell version v3.6.23
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
2021-12-15T13:06:09.687-0600 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(socket), reason: Permission denied
2021-12-15T13:06:09.687-0600 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:275:13
@(connect):1:6
exception: connect failed

**Notes:**
No issues yesterday when on 4.1.2 snap, auto upgrade overnight, shell access now broken.
After working through this fix (https://github.com/RocketChat/rocketchat-server-snap/issues/31) the chat platform seems to be working correctly.

**Comment by debdutdeb** [comment]
I have a guess why this might be happening, do you need it fixed right away? Otherwise I'd like to release it with some other changes.

**Comment by bleschber** [comment]
It can wait

**Comment by bleschber** [comment]
@debdutdeb what is your current eta for the release of fixes that will address this?

**Comment by debdutdeb** [comment]
Hey, could you please update to the latest and see if this issue still persists or not? Thanks :)

**Comment by bleschber** [comment]
This has been fixed now.  I have confirmed it works again in 4.3.1.  Thanks
