### ISSUE TITLE
rocketchat-server.backupdb error after 1502 upgrade (ubuntu 20)

### ISSUE THREAD

**Issue by ggoidin** [RocketChat/rocketchat-server-snap#33]
Daily cron job return errors since this update : 

snap stop rocketchat-server.rocketchat-server => Stopped.
systemctl is-active snap.rocketchat-server.rocketchat-server => inactive
snap run rocketchat-server.backupdb

=> [-] Please shutdown Rocket.Chat first to get a clean backup
=>[-] Use 'sudo snap stop rocketchat-server.rocketchat-server'
=>/snap/rocketchat-server/1502/bin/backupdb.sh: line 24: log: command not found
=>/snap/rocketchat-server/1502/bin/backupdb.sh: line 26: log: command not found
=>/snap/rocketchat-server/1502/bin/backupdb.sh: line 28: log: command not found

The generated backup is not consistent since directory "dump" is empty.

/snap/rocketchat-server/1502/bin/backupdb.sh does not contain any log function.

**Comment by shacky** [comment]
Same for me - there are two issues: stop doesn't delete PID file and there is no log command (or bash function).
```console
root@support:/usr/local/sbin# snap stop rocketchat-server.rocketchat-server
Stopped.
root@support:/usr/local/sbin# ls -l /var/snap/rocketchat-server/common/rocketchat.pid
-rw-r--r-- 1 root root 6 Dec 23 10:00 /var/snap/rocketchat-server/common/rocketchat.pid
root@support:/usr/local/sbin# ps ax | grep rocket
14789 pts/1    S+     0:00 grep rocket
17473 ?        Sl   146:23 mongod --config=/var/snap/rocketchat-server/1502/mongod.conf --fork --syslog
root@support:/usr/local/sbin# snap run rocketchat-server.backupdb
[-] Please shutdown Rocket.Chat first to get a clean backup
[-] Use 'sudo snap stop rocketchat-server.rocketchat-server'
/snap/rocketchat-server/1502/bin/backupdb.sh: line 24: log: command not found
/snap/rocketchat-server/1502/bin/backupdb.sh: line 26: log: command not found
/snap/rocketchat-server/1502/bin/backupdb.sh: line 28: log: command not found
dump/
[+] A backup of your data can be found at /var/snap/rocketchat-server/common/backup/rocketchat_backup_20211223.1000.tar.gz
```

**Comment by bingovivi** [comment]
root@vmi777:~# sudo snap run rocketchat-server.backupdb
[-] Please shutdown Rocket.Chat first to get a clean backup
[-] Use 'sudo snap stop rocketchat-server.rocketchat-server'
/snap/rocketchat-server/1502/bin/backupdb.sh: line 24: log: command not found
/snap/rocketchat-server/1502/bin/backupdb.sh: line 26: log: command not found
/snap/rocketchat-server/1502/bin/backupdb.sh: line 28: log: command not found
dump/
[+] A backup of your data can be found at /var/snap/rocketchat-server/common/backup/rocketchat_backup_20211230.1611.tar.gz

me too lol, pls help !

**Comment by ggoidin** [comment]
I'm a little worried, we haven't had a backup for 15 days because of this bug.
Do you think we should stop using snap?

**Comment by bingovivi** [comment]
> I'm a little worried, we haven't had a backup for 15 days because of this bug. Do you think we should stop using snap?

I have rolled back to the previous 4.1.2 version , backup mongodb and move it to docker . 

now Rocket.chat is 4.3.1
MongoDB 4.0.27

sudo snap revert rocketchat-server
rocketchat-server reverted to 4.1.2

backup db , then transfer it to docker and recovery it. done.

refer to this article : https://www.networktechguy.com/posts/post-0009/

Good luck!

**Comment by debdutdeb** [comment]
Hey guys, this is fixed in the latest release yesterday.

**Comment by debdutdeb** [comment]
Fixed in https://github.com/RocketChat/rocketchat-server-snap/commit/2525b551390c4ba9dcd274e7e30db0a406e085af and released to 4.x track. Closing this now.
