### ISSUE TITLE
rcrestore is broken

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/rocketchat-server-snap#4]
Bad system call during restore, see trace below.  

Also, a bad restore seems to result in success message.

```
*** ATTENTION ***
* Your current database WILL BE DROPPED prior to the restore!
* Would you like to make a backup of the current database before proceeding?
* (y/n/Q)> y
tar: Removing leading `/' from member names
A backup of your data can be found at /root/snap/rocketchat-server/common/backups/rocketchat_backup_1486104024.tgz.
Extracting backup file...
/snap/rocketchat-server/x1/bin/rcrestore: line 44: 17058 Bad system call         tar zxvf $1 &> "$restore_dir/$log_name"
Cleaning database...
Restoring data...
Restore completed! Please restart the snap.rocketchat services to verify.
```

**Comment by elespike** [comment]
Hm, this is an issue I was seeing when the backup file was outside of a directory accessible by the snap, hence the logic to check the backup file location.

I'll investigate.

**Comment by elespike** [comment]
@Sing-Li, did you happen to run this as root, using `sudo`? That's the only way I can recreate the issue.

If that's the case, I know what the issue is and can probably fix it quickly.

**Comment by Sing-Li** [comment]
@elespike  - very possibly 😃     Up until this revision, backup was also done via `sudo`.   

I do believe admin will be the ones starting, stopping, doing backup / restore etc with the server - so I think sudo is fine.  Especially since install and start and journalctl (view logs) require it (to have a consistent experience).

**Comment by elespike** [comment]
Agreed. Give me some time. =)

**Comment by elespike** [comment]
PR #8 created after much testing (do test more by all means)

**Comment by Sing-Li** [comment]
I will close after some testing here.  Thanks.

**Comment by Sing-Li** [comment]
Still has some problems, please see trace:

```
autoqa@vps105588:~/rocketchat-server-snap$ sudo snap run rocketchat-server.restoredb /var/snap/rocketchat-server/common/backup.tgz
*** ATTENTION ***
* Your current database WILL BE DROPPED prior to the restore!
* Would you like to make a backup of the current database before proceeding?
* (y/n/Q)> y
tar: Removing leading `/' from member names
[+] A backup of your data can be found at /var/snap/rocketchat-server/common/backups/rocketchat_backup_2017-02-05_16-34-08.tgz.
[*] Extracting backup file...
[*] Restoring data...
/snap/rocketchat-server/x1/bin/rcrestore: line 60: 23023 Aborted                 (core dumped) mongorestore --db parties --drop ${data_dir} &> "${restore_dir}/${log_name}"
[!] Failed to execute mongorestore from var/snap/rocketchat-server/451/dump/parties!
[*] Check /var/snap/rocketchat-server/common/restore/mongorestore.log for details.
[-] Restore aborted!
```

Looking into the logs:

```
2017-02-05T16:34:09.042-0500 	Creating index: { key: { editedBy._id: 1 }, name: "editedBy._id_1", ns: "parties.rocketchat_message", sparse: 1 }
2017-02-05T16:34:09.043-0500 	Creating index: { key: { rid: 1, t: 1, u._id: 1 }, name: "rid_1_t_1_u._id_1", ns: "parties.rocketchat_message" }
2017-02-05T16:34:09.044-0500 	Creating index: { key: { expireAt: 1 }, name: "expireAt_1", ns: "parties.rocketchat_message", expireAfterSeconds: 0 }
2017-02-05T16:34:09.045-0500 	Creating index: { key: { _fts: "text", _ftsx: 1 }, name: "msg_text", ns: "parties.rocketchat_message", weights: { msg: 1 }, default_language: "english", language_override: "language", textIndexVersion: 3 }
Error creating index parties.rocketchat_message: 16730 err: "bad textIndexVersion: 3"
```
For your information, I am using a backup from the previous version of the snap (not created by this new rcbackup).

**Comment by elespike** [comment]
Oh, I actually saw this issue when I was creating rcrestore. I "fixed" it by editing the mongodump files and changing textIndexVersion to 1 and then promptly forgot about it.

That was obviously a hack, so I'll try to find out what's this `textIndexVersion` thing and why mongorestore doesn't like it (even though mongodump created it).

**Comment by elespike** [comment]
@Sing-Li Would you mind retesting with #9 ?
I no longer have previous backups that were failing that way.

**Comment by Sing-Li** [comment]
👍    Will test !    Thanks.

**Comment by Sing-Li** [comment]
Verified working!   Thanks @elespike !    I'll close this.

The latest version , pix upload doesn't seem to work - but that's a totally unrelated issue :)
