### ISSUE TITLE
backup file name should have date component

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/rocketchat-server-snap#5]
Currently, the backup filename has a unique id  (for example - rocketchat_backup_1486104024.tgz).

Adding a human readable date component to it will help with backup management.  (for example - rocketchat_backup_01_18_2017_23_30_1488232.tgz).

**Comment by elespike** [comment]
That ID is really "seconds since the epoch", so it's a date, just not human-readable. I went with that because I wanted to include hours and minutes, but working with `:` in file names is annoying.

Do you think month and day are enough?

**Comment by Sing-Li** [comment]
There is probably value to add year, hour and minutes as well.   For the use case of automated backup scripts , and during testing where we're creating multiple backup in rapid succession.

**Comment by elespike** [comment]
The epoch time is down to seconds and includes timezone info as well. Here's a conversion example:

```
#! /bin/bash

echo "Given file name is '$1'"
epoch=${1:18:-4}
echo "Epoch date is '$epoch'"
date=$(date -d @$epoch)
echo "Date is $date"
```

Output:
```
Given file name is 'rocketchat_backup_1486234335.tgz'
Epoch date is '1486234335'
Date is Sat Feb  4 13:52:15 EST 2017
```

**Comment by Sing-Li** [comment]
Something similar to `rocketchat_backup_2017_02_10_23_30_148.tgz`  will be friendly for administrators who may not be developers or have access to conversion routines.

**Comment by elespike** [comment]
PR #7 created; date looks like: `rocketchat_backup_2017-02-05_00-28-15.tgz`

**Comment by Sing-Li** [comment]
Thanks.  Will test and close this one tonight.

**Comment by Sing-Li** [comment]
Thanks!  Verified working.  Closing this issue.
